---
title: "Seafood Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: embed
    #runtime: shiny
    output: html_document
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(lubridate)
library(vroom)
library(tidyverse)
#library(shiny)
library(DT)
library(crosstalk)
library(kableExtra)

```


```{r global, include=FALSE}
## Loading data
df_Seafood <- vroom("Seafood-database_preliminary.csv")

## processing data
# Turning Character columns in Factors. But first selecting all columns of class = Character
# https://stackoverflow.com/questions/33180058/coerce-multiple-columns-to-factors-at-once
df_Seafood[map_lgl(df_Seafood, is.character)] <- lapply(df_Seafood[map_lgl(df_Seafood, is.character)], factor)

#### turning Year in to date.year
## Issue here. We only have years, and that is not a valid date format for plotting. But, since the values are annual sum. But, for plotting it looks better using the 1st of Jan. If we would use e.g. the 31.12.2019, it would look like the data is for 2020 :( 

df_Seafood$Year <-dmy(as.character(paste("01-01",df_Seafood$Year)))

#df_Seafood_shared <- SharedData$new(df_Seafood)

df_UKPOP <- vroom("ONS_UK_population-19712020.csv")
df_UKPOP$Year <-dmy(as.character(paste("01-01",df_UKPOP$CDID)))



```

```{r sunburst data wrangling, include=FALSE}
### We are trying to build a sunburst plot from our import export dataset
## the data needs to have the following structure ids, labels, parents, values
## values need to be the total of each ids e.g. Export all fish exported

## Start with import and exports

df_Seafood %>% group_by(ids = Commodity) %>%  summarise(values = sum(na.omit(Volume)))
df_Seafood %>% group_by(parents = Commodity, ids = SpeciesType) %>%  summarise(values = sum(na.omit(Volume)))
df_Seafood %>% group_by(Commodity, parents = SpeciesType, ids = Species) %>%  summarise(values = sum(na.omit(Volume)))


## Import & Export sums
df_sunburst <- df_Seafood %>% 
  group_by(ids = as.character(Commodity)) %>% 
  summarise(values = sum(na.omit(Volume))) %>% 
  mutate(labels = ids, parents ="")


## Species Type sums
df_sunburst.temp <-df_Seafood %>% 
  group_by(parents = as.character(Commodity), labels = as.character(SpeciesType)) %>% 
  summarise(values = sum(na.omit(Volume))) %>% 
  mutate(ids = paste(parents," - ", labels)) # to create unique ids


df_sunburst <- rbind(df_sunburst,df_sunburst.temp)

## Species sums
df_sunburst.temp <- df_Seafood %>% 
  group_by(Commodity, SpeciesType, labels = as.character(Species)) %>% 
  summarise(values = sum(na.omit(Volume))) %>% 
  ungroup() %>% 
  mutate(parents = paste(Commodity," - ", SpeciesType),
         ids = paste(Commodity," - ", SpeciesType, " - ", labels)) %>% 
  select(ids, labels, parents, values)

df_sunburst <- rbind(df_sunburst,df_sunburst.temp)

### last one years (no calucation)
df_sunburst.temp <- df_Seafood %>% 
  select(Commodity, SpeciesType, Species, Year, Volume) %>% 
  mutate(parents = paste(Commodity," - ", SpeciesType, " - ", Species),
         ids = paste(Commodity," - ", SpeciesType, " - ", Species, " - ", Year),
         labels = lubridate::year(Year),
         values = Volume) %>% 
  select(ids, labels, parents, values)

df_sunburst <- rbind(df_sunburst,df_sunburst.temp)

df_Seafood.cp <- df_Seafood %>% filter(Species %in% c("Cod", "Haddock", "Prawns", "Tuna", "Salmon", "Mackerel", "Herring"))

## "Consumption" & "Purchases sums
df_sunburst.cp <- df_Seafood.cp %>% 
  group_by(ids = as.character(Commodity)) %>% 
   summarise(values = sum(na.omit(Volume))) %>% 
  mutate(labels = ids, parents ="")


## Species Type sums
df_sunburst.temp <-df_Seafood.cp %>% 
  group_by(parents = as.character(Commodity), labels = as.character(SpeciesType)) %>% 
   summarise(values = sum(na.omit(Volume))) %>% 
  mutate(ids = paste(parents," - ", labels)) # to create unique ids


df_sunburst.cp <- rbind(df_sunburst.cp,df_sunburst.temp)

## Species sums
df_sunburst.temp <- df_Seafood.cp %>% 
  group_by(Commodity, SpeciesType, labels = as.character(Species)) %>% 
   summarise(values = sum(na.omit(Volume))) %>% 
  ungroup() %>% 
  mutate(parents = paste(Commodity," - ", SpeciesType),
         ids = paste(Commodity," - ", SpeciesType, " - ", labels)) %>% 
  select(ids, labels, parents, values)

df_sunburst.cp <- rbind(df_sunburst.cp,df_sunburst.temp)

### last one years (no calucation)
df_sunburst.temp <- df_Seafood.cp %>% 
  select(Commodity, SpeciesType, Species, Year, Volume) %>% 
  mutate(parents = paste(Commodity," - ", SpeciesType, " - ", Species),
         ids = paste(Commodity," - ", SpeciesType, " - ", Species, " - ", Year),
         labels = lubridate::year(Year),
         values = Volume) %>% 
  select(ids, labels, parents, values)

df_sunburst.cp <- rbind(df_sunburst.cp,df_sunburst.temp)


```

```{r table Data availablity}

df_SF_availablity <- df_Seafood %>% select(Species, Commodity) %>%
  unique() %>% 
  mutate(Available = "Yes") %>% 
  pivot_wider(names_from = Commodity, 
              values_from = Available,
              values_fill = "No") %>% 
  mutate(Exports = as.factor(Exports),
         Imports = as.factor(Imports),
         Production = as.factor(Production),
         Consumption = as.factor(Consumption),
         Purchases = as.factor(Purchases))



```

```{r all species through year}

df_figure <- df_Seafood %>% select(Commodity, Species, SACN, Year, Volume, Units) %>% group_by(Commodity, Species, SACN, Year) %>% summarise(Volume = sum(Volume)) %>% mutate(Year_notDate = as.numeric(year(Year))) %>% left_join(df_UKPOP %>%  select(CDID, UKPOP), by = join_by(Year_notDate == CDID)) %>% mutate( Volume = Volume/UKPOP) %>% pivot_wider(names_from = Commodity, values_from = Volume)

#Subplots for chart 3
fig1 <-df_figure %>%  plot_ly(type = 'bar', x=~Year, y=~Exports, color = ~Species, legendgroup =~Species) %>% 
  layout(yaxis = list(title = "Volume [g/Capita]"))
fig2 <-df_figure %>%  plot_ly(type = 'bar', x=~Year, y=~Imports, color = ~Species, legendgroup =~Species, showlegend= FALSE)%>% 
  layout(yaxis = list(title = "Volume [g/Capita]"))
fig3 <-df_figure %>%  plot_ly(type = 'bar', x=~Year, y=~Production, color = ~Species, legendgroup =~Species, showlegend= FALSE)%>% 
  layout(yaxis = list(title = "Volume [g/Capita]"))
fig4 <-df_figure %>%  plot_ly(type = 'bar', x=~Year, y=~Consumption, color = ~Species, legendgroup =~Species, showlegend= FALSE) %>% 
  layout(yaxis = list(title = "Volume [g/Capita]"))
fig5 <-df_figure %>%  plot_ly(type = 'bar', x=~Year, y=~Purchases, color = ~Species, legendgroup =~Species, showlegend= FALSE) %>% 
  layout(yaxis = list(title = "Volume [g/Capita]"), xaxis = list(title = "Years"))

```


Dashboard
=======================================================================

## Row {.sidebar}



```{r filter, eval=FALSE, include=FALSE}

# https://stackoverflow.com/questions/45887038/plot-simple-chart-on-the-basis-of-data-subset-in-flexdashboard
#selectInput("selectInput1", "Select Species Type:", 
          #  choices = unique(df_Seafood$SpeciesType))

#electInput("selectInput2", "Select Commodity:", 
           # choices = unique(df_Seafood$Commodity))

#input


filter_checkbox("Commodity", "Choose Import or Export", df_Seafood_shared, ~Commodity)
filter_select("SpeciesType", "Choose Species Type", df_Seafood_shared, ~SpeciesType)
```

```{r}
# Create a subset data frame 
#selectedData = reactive({df_Seafood %>% filter(SpeciesType == as.character(input$selectInput1), Commodity == as.character(input$selectInput2)) 
  
 #  })
```


## Row {.tabset .tabset-fade}
### Table 1 Data availablitiy

Table 1 shows which commodity data is available for which species in the seafood database.The Seafood data base contains a decade worth (2009 - 2020) of data for 88 marine species.

```{r table 1 kable color }
df_SF_availablity %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = c("striped", "condensed", "responsive")) %>% 
  column_spec(2, color = "white", background = ifelse(df_SF_availablity$Exports == "Yes",  "green", "red")) %>% 
  column_spec(3, color = "white", background = ifelse(df_SF_availablity$Imports == "Yes", "green", "red")) %>% 
  column_spec(4, color = "white", background = ifelse(df_SF_availablity$Production == "Yes", "green", "red")) %>% 
  column_spec(5, color = "white", background = ifelse(df_SF_availablity$Consumption == "Yes", "green", "red")) %>% 
  column_spec(6, color = "white", background = ifelse(df_SF_availablity$Purchases == "Yes", "green", "red"))



```


### Chart 1 Sunburst chart

```{r Chart 1 Sunburst chart}
layout(plot_ly(df_sunburst,
               ids = ~ids,
               labels = ~labels,
               parents = ~parents,
               values = ~values,
               type = 'sunburst',
               branchvalues = 'total'
), colorway = c("#009E73", "#0072B2", "#56B4E9" ,"#E69F00", "#F0E442" ))

```

### Chart 2 Sunburst 5 Species

```{r Chart 2 Sunburst Consumption & Purchase}

layout(plot_ly(df_sunburst,
               ids = ~ids,
               labels = ~labels,
               parents = ~parents,
               values = ~values,
               type = 'sunburst',
               branchvalues = 'total'
), colorway = c("#009E73", "#0072B2", "#56B4E9" ,"#E69F00", "#F0E442" ))
```

### Chart 3 Commodity data

```{r Chart 3 Commodity data}
#help for check out https://plotly.com/r/subplots/

subplot(fig1, fig2, fig3, fig4, fig5, nrows = 5, shareX = TRUE, titleY = TRUE) %>% 
  layout(yaxis = list(
    zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'),
    annotations = list( 
  list( 
    x = 0.1,  
    y = 1.0,  
    text = "UK Exports",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.1,  
    y = 0.79,  
    text = "UK Imports",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.1,  
    y = 0.58,  
    text = "UK Production",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 0.1,  
    y = 0.39,  
    text = "UK Consumption",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
   list( 
    x = 0.1,  
    y = 0.19,  
    text = "UK Purchases",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ) )
  )

 
  


```




```{r Chart 5 Sankey, eval=FALSE, include=FALSE}

df_test <- df_Seafood %>% select(Commodity, SACN, Year, Volume) %>% filter(Year == "2018-01-01") %>% 
  filter(Commodity %in% c("Exports","Imports", "Production", "Purchases")) %>%
  group_by(SACN, Commodity) %>% summarise(Volume = sum(Volume, na.rm = TRUE))



plot_ly(
  type = "sankey",
  orientation = "h",
  node = list(
    label = c("Product"	,"Import",	"Lean",	"Oily",	"Other",	"Shellfish",	"Export",	"Purchase"),
    color = c("green", "red", "blue", "blue", "blue", "blue","lightblue", "lightgreen"),
    pad = 15,
    thickness = 20,
    line = list(
      color = "black",
      width = 0.5
    )
  ),
  
  link = list(
    source = c(2,1,0,2,3,1,0,3,4,1,0,4,5,1,0,5),
    target = c(6,2,2,7,6,3,3,7,6,4,4,7,6,5,5,7),
    value =  df_test$Volume
  )
)


```

Key Messages
=======================================================================


About
=======================================================================

Source
=======================================================================

Related Publication
=======================================================================